# Generated by Django 5.2.3 on 2025-06-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('tmax', models.FloatField(blank=True, null=True)),
                ('tmin', models.FloatField(blank=True, null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('station_id', 'date')},
            },
        ),
    ]
